ag_vault_folder_index:
    path: /
    defaults:
        _controller: AGVaultBundle:Folder:index

ag_vault_folder_show:
    path: /{id}-{slug}
    defaults:
        _controller: AGVaultBundle:Folder:show
        slug: null
    requirements:
        id: \d+
        slug: "[a-zA-Z0-9-_/]+"

ag_vault_folder_remove:
    path: /{id}/remove
    defaults:
        _controller: AGVaultBundle:Folder:remove
    requirements:
        id: \d+

ag_vault_folder_rename:
    path: /{id}/rename
    defaults:
        _controller: AGVaultBundle:Folder:rename
    requirements:
        id: \d+

ag_vault_folder_move:
    path: /{id}/move
    defaults:
        _controller: AGVaultBundle:Folder:move
    requirements:
        id: \d+

ag_vault_folder_get_parents:
    path: /{id}/get-parents
    defaults:
        _controller: AGVaultBundle:Folder:getParents
    requirements:
        id: \d+
