<?php

namespace AG\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findRegularUsers()
    {
        $qb = $this->createQueryBuilder('u');

        $qb
            ->where($qb->expr()->notLike('u.roles', $qb->expr()->literal('%ROLE_ADMIN%')))
            ;

        return $qb->getQuery()->getResult();
    }
}
