<?php

namespace AG\UserBundle\Repository;

use AG\UserBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function myFindAll(User $user)
    {
        $qb = $this->createQueryBuilder('u');

        $qb
            ->where('u.id != :id')
            ->andWhere($qb->expr()->notLike('u.roles', $qb->expr()->literal('%ROLE_SUPER_ADMIN%')))
            ->setParameter('id', $user->getId())
            ;

        return $qb->getQuery()->getResult();
    }
}
