# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    font_awesome_extension:
        class: AG\VaultBundle\Twig\FontAwesomeExtension
        tags:
            - { name: twig.extension }

    date_fr_extension:
        class: AG\VaultBundle\Twig\DateFrExtension
        tags:
            - { name: twig.extension }

    size_reformat_extension:
        class: AG\VaultBundle\Twig\SizeReformatExtension
        tags:
            - { name: twig.extension }

    api_key_authenticator:
            class:  AG\ApiBundle\Security\ApiKeyAuthenticator
            public: false

    api_key_user_provider:
        class: AG\ApiBundle\Security\ApiKeyUserProvider
        arguments: [@fos_user.user_manager]
