<?php

namespace AG\VaultBundle\Repository;

use AG\UserBundle\Entity\User;
use AG\VaultBundle\Entity\Folder;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * FolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FolderRepository extends EntityRepository
{
    public function findSearch($search, $user)
    {
        $qb = $this->createQueryBuilder('f')
            ->orderBy('f.name', 'ASC')
            ->where('f.owner = :user')
            ->setParameter('user', $user)
        ;

        $search = trim($search);
        $words = explode(' ', $search);

        foreach ($words as $key => $word)
        {
            $qb
                ->andWhere(
                    $qb->expr()->like('f.name', ":word$key")
                )
                ->setParameter("word$key", "%$word%")
            ;
        }

        return $qb->getQuery()->getResult();
    }

    /**
     *
     * API custom functions
     *
     */

    public function apiFindAll($user)
    {
        $qb = $this
            ->createQueryBuilder('f')
            ->where('f.owner = :user')
            ->setParameter('user', $user)
            ->orderBy('f.name', 'ASC')
        ;

        return $qb->getQuery()->getArrayResult();
    }

    public function apiFindBy($folder, $user)
    {
        $qb = $this
            ->createQueryBuilder('f0')
            ->addSelect('f1.name')
            ->addSelect('COUNT(f2.id) nbr_folders')
            ->addSelect('COUNT(f3.id) nbr_files')
            ->innerJoin('f0.children', 'f1', Join::WITH, 'f1.parent = f0.id')
            ->innerJoin('f1.children', 'f2', Join::WITH, 'f2.parent = f1.id')
            ->leftJoin('f1.files', 'f3', Join::WITH, 'f3.folder = f1.id')
            ->where('f1.parent = :folder')
            ->andWhere('f0.owner = :user')
            ->setParameters(array(
                'folder' => $folder,
                'user' => $user
            ))
            ->groupBy('f1.id')
            ->orderBy('f1.name', 'ASC')
        ;

        return $qb->getQuery()->getArrayResult();
    }
}
