<?php

namespace AG\VaultBundle\Repository;

use AG\UserBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * ShareLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShareLinkRepository extends EntityRepository
{
    public function findShareFiles(User $user)
    {
        $qb = $this->createQueryBuilder('s')
            ->addSelect('f')
            ->join('s.file', 'f')
            ->where('f.owner = :id')
            ->setParameter('id', $user->getId())
            ->getQuery()
            ->getArrayResult()
        ;

        return $qb;
    }
}
