<?php

namespace AG\VaultBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ShareLinkController__JMSInjector
{
    public static function inject($container) {
        require_once __DIR__ . '/../proxies/AG-VaultBundle-Controller-ShareLinkController.php';
        $d = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('AG\\VaultBundle\\Controller\\ShareLinkController' => array('allAction' => array(0 => 'security.access.method_interceptor'), 'removeAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxyc20a4599_98c2eb7da9fbe61972bb4fbc5994d96422b978f3\__CG__\AG\VaultBundle\Controller\ShareLinkController();
        $instance->__CGInterception__setLoader($d);
        $refProperty = new \ReflectionProperty('AG\\VaultBundle\\Controller\\ShareLinkController', 'em');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('doctrine.orm.entity_manager', 1));
        $refProperty = new \ReflectionProperty('AG\\VaultBundle\\Controller\\ShareLinkController', 'request');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('request', 1));
        return $instance;
    }
}
