<?php

namespace EnhancedProxy84764c5e_de971009d60115fd642b03aadb323bba69cc0951\__CG__\AG\UserBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AdminController__JMSInjector
{
    public static function inject($container) {
        require_once __DIR__ . '/../proxies/AG-UserBundle-Controller-AdminController.php';
        $j = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('AG\\UserBundle\\Controller\\AdminController' => array('indexAction' => array(0 => 'security.access.method_interceptor'), 'addAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'removeAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy84764c5e_de971009d60115fd642b03aadb323bba69cc0951\__CG__\AG\UserBundle\Controller\AdminController();
        $instance->__CGInterception__setLoader($j);
        $refProperty = new \ReflectionProperty('AG\\UserBundle\\Controller\\AdminController', 'em');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('doctrine.orm.entity_manager', 1));
        $refProperty = new \ReflectionProperty('AG\\UserBundle\\Controller\\AdminController', 'request');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('request', 1));
        return $instance;
    }
}
