<?php

namespace Symfony\Bundle\AsseticBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AsseticController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Symfony\Bundle\AsseticBundle\Controller\AsseticController();
        $refProperty = new \ReflectionProperty('Symfony\\Bundle\\AsseticBundle\\Controller\\AsseticController', 'request');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('request', 1));
        return $instance;
    }
}
