ag_vault_homepage:
    path:     /
    defaults:
        _controller: AGVaultBundle:Folder:show

ag_vault_upload:
    path: /upload
    defaults:
        _controller: AGVaultBundle:File:upload

ag_vault_folder:
    resource: "routing/folder.yml"
    prefix: /folder

ag_vault_file:
    resource: "routing/file.yml"
    prefix: /file

ag_vault_share_link:
    resource: "routing/share_link.yml"
    prefix: /share-link
